### ISSUE TITLE
Error with inflate stream

### ISSUE THREAD

**Issue by dnomadb** [mapbox/trizilla#14]
This does not seem to be hurting the output, which leads me to believe that this is probably due to a pipe not being fully flushed or smth:

```

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at InflateStream._transform (/Users/dnomadb/tri-zilla/index.js:19:27)
    at InflateStream.Transform._read (_stream_transform.js:179:10)
    at InflateStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at InflateStream.Writable.write (_stream_writable.js:182:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:95:17)
    at drain (/Users/dnomadb/node_modules/split/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/dnomadb/node_modules/split/node_modules/through/index.js:45:5)
    at emit (/Users/dnomadb/node_modules/split/index.js:36:14)
    at Stream.<anonymous> (/Users/dnomadb/node_modules/split/index.js:59:7)
    at _end (/Users/dnomadb/node_modules/split/node_modules/through/index.js:65:9)
```

cc: @ian29

**Comment by ian29** [comment]
this is usually due to an extra newline and the end of a ~~file~~ input stream @dnomadb.

**Comment by ian29** [comment]
@dnomadb can you package a up a test case this? im having trouble reliably replicating.

**Comment by dnomadb** [comment]
@ian29 of course. It most likely has to do with the output from db-read; should I just `gist` this then you can `cat` it, or do you want to try from a dynalite db yourself?

**Comment by ian29** [comment]
@dnomadb ok but can we close **this** one? this is fixed by your pipecleaner right?

**Comment by dnomadb** [comment]
Y!
