### ISSUE TITLE
adapt to node-mapnik 3.1.5

### ISSUE THREAD

**Issue by springmeyer** [mapbox/trizilla#17]
Node-mapnik 3.1.5 requires registering the `geojson.input` for `vtile.addGeoJSON` to work, so I recommend the below in order to keep working with node 3.1.4 and 3.1.5.

``` diff
diff --git a/index.js b/index.js
index 53090a0..61d15ef 100644
--- a/index.js
+++ b/index.js
@@ -7,6 +7,7 @@ var Aggregator = require('./lib/aggregator');
 var tiler = require('./lib/tiler');
 var inflator = require('./lib/inflator');
 mapnik.register_datasource(path.join(mapnik.settings.paths.input_plugins,'ogr.input'));
+mapnik.register_datasource(path.join(mapnik.settings.paths.input_plugins,'geojson.input'));

 module.exports = function() {
   var parentHolder = {}
```

Note: i would have committed directly but the tests in master are broken so I hesitated to make **any** changes:

```
/Users/dane/projects/trizilla/test/lay-tiles.test.js:15
trizilla.layTiles.initTiler(5, tileCallback);
                  ^
TypeError: Cannot call method 'initTiler' of undefined
    at Object.<anonymous> (/Users/dane/projects/trizilla/test/lay-tiles.test.js:15:19)
    at Module._compile (module.js:456:26)

```

**Comment by dnomadb** [comment]
Thanks @springmeyer - integrating the changes here: https://github.com/mapbox/trizilla/pull/16

**Comment by springmeyer** [comment]
great
